"""
Real training loop for ResNet-34 U-Net lesion segmenter.

Learns from pseudo-masks generated by training/generate_pseudo_masks.py
(mask convention: 0=background, 1=leaf, 2=lesion).
"""
import os
import sys
import json
import argparse
import time
import random

import numpy as np
from PIL import Image, ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, random_split
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingLR

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if BASE_DIR not in sys.path:
    sys.path.insert(0, BASE_DIR)

from models.unet_segmenter import ResNet34_UNet


class SegmentationDataset(Dataset):
    """Pairs images from MAIN DATA/Train/<class> with pseudo-masks from SegMasks/<class>."""
    def __init__(self, data_dir: str, mask_dir: str, img_size: int = 256):
        self.pairs = []
        self.img_size = img_size

        for cls in sorted(os.listdir(mask_dir)):
            mask_cls_dir = os.path.join(mask_dir, cls)
            if not os.path.isdir(mask_cls_dir):
                continue
            img_cls_dir = os.path.join(data_dir, "Train", cls)
            if not os.path.isdir(img_cls_dir):
                continue
            for mfile in os.listdir(mask_cls_dir):
                if not mfile.endswith("_mask.png"):
                    continue
                base = mfile[:-len("_mask.png")]
                for ext in (".jpg", ".jpeg", ".png", ".JPG", ".PNG"):
                    cand = os.path.join(img_cls_dir, base + ext)
                    if os.path.exists(cand):
                        self.pairs.append((cand, os.path.join(mask_cls_dir, mfile)))
                        break

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, idx):
        img_path, mask_path = self.pairs[idx]
        img = Image.open(img_path).convert("RGB").resize((self.img_size, self.img_size), Image.Resampling.BILINEAR)
        mask = Image.open(mask_path).resize((self.img_size, self.img_size), Image.Resampling.NEAREST)

        img = np.array(img, dtype=np.float32) / 255.0
        img = (img - [0.485, 0.456, 0.406]) / [0.229, 0.224, 0.225]
        img = torch.from_numpy(img.transpose(2, 0, 1)).float()

        m = np.array(mask)
        leaf = (m == 1).astype(np.float32)
        lesion = (m == 2).astype(np.float32)
        target = torch.from_numpy(np.stack([leaf, lesion])).float()
        return img, target


class DiceBCELoss(nn.Module):
    """Combined Dice and Binary Cross Entropy Loss for segmentation."""
    def __init__(self, dice_weight: float = 1.0, bce_weight: float = 1.0, leaf_weight: float = 1.0):
        super().__init__()
        self.dice_weight = dice_weight
        self.bce_weight = bce_weight
        self.leaf_weight = leaf_weight

    @staticmethod
    def _dice(inputs, targets, smooth=1.0):
        inputs = torch.sigmoid(inputs)
        inter = (inputs * targets).sum(dim=(2, 3))
        denom = inputs.sum(dim=(2, 3)) + targets.sum(dim=(2, 3))
        return 1 - ((2 * inter + smooth) / (denom + smooth)).mean()

    def forward(self, logits, targets):
        # Channel 0: leaf (weighted up; it dominates area), Channel 1: lesion
        pos_weight = torch.tensor([self.leaf_weight, 1.0], device=logits.device)
        bce = nn.functional.binary_cross_entropy_with_logits(logits, targets, pos_weight=pos_weight)
        dice = self._dice(logits, targets)
        return self.bce_weight * bce + self.dice_weight * dice


def iou_score(logits, targets, thresh=0.5):
    preds = (torch.sigmoid(logits) > thresh).float()
    inter = (preds * targets).sum(dim=(0, 2, 3))
    union = preds.sum(dim=(0, 2, 3)) + targets.sum(dim=(0, 2, 3)) - inter
    return (inter / union.clamp(min=1)).mean().item()


def get_safe_device():
    if torch.cuda.is_available():
        try:
            probe = (torch.ones(1, device="cuda") + 1).cpu()
            if probe.item() == 2:
                return torch.device("cuda")
        except Exception as e:
            print(f"[Device] CUDA probe failed ({e}). CPU fallback.")
    return torch.device("cpu")


def main():
    parser = argparse.ArgumentParser(description="Train ResNet-34 U-Net lesion segmenter on pseudo-masks")
    parser.add_argument("--data_dir", type=str, default="MAIN DATA")
    parser.add_argument("--mask_dir", type=str, default="MAIN DATA/SegMasks")
    parser.add_argument("--output_dir", type=str, default="weights")
    parser.add_argument("--epochs", type=int, default=15)
    parser.add_argument("--batch_size", type=int, default=12)
    parser.add_argument("--lr", type=float, default=3e-4)
    parser.add_argument("--img_size", type=int, default=256)
    parser.add_argument("--val_ratio", type=float, default=0.15)
    parser.add_argument("--num_workers", type=int, default=4)
    parser.add_argument("--resume", action="store_true", default=True)
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)
    device = get_safe_device()
    torch.backends.cudnn.benchmark = True
    print(f"[U-Net Training] Device: {device}")

    ds = SegmentationDataset(args.data_dir, args.mask_dir, img_size=args.img_size)
    if len(ds) == 0:
        print("[Error] No image/mask pairs found. Run training/generate_pseudo_masks.py first.")
        sys.exit(1)
    print(f"[U-Net Training] {len(ds)} image/mask pairs")

    n_val = int(len(ds) * args.val_ratio)
    n_train = len(ds) - n_val
    train_ds, val_ds = random_split(ds, [n_train, n_val], generator=torch.Generator().manual_seed(42))

    train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True,
                              num_workers=args.num_workers, pin_memory=(device.type == "cuda"),
                              persistent_workers=(args.num_workers > 0))
    val_loader = DataLoader(val_ds, batch_size=args.batch_size, shuffle=False,
                            num_workers=args.num_workers, pin_memory=(device.type == "cuda"),
                            persistent_workers=(args.num_workers > 0))

    model = ResNet34_UNet(out_channels=2, pretrained=True).to(device)
    criterion = DiceBCELoss(dice_weight=1.0, bce_weight=1.0, leaf_weight=1.5)
    optimizer = AdamW(model.parameters(), lr=args.lr, weight_decay=1e-4)
    scheduler = CosineAnnealingLR(optimizer, T_max=args.epochs, eta_min=1e-6)
    scaler = torch.amp.GradScaler("cuda") if device.type == "cuda" else None

    ckpt_path = os.path.join(args.output_dir, "unet_checkpoint.pt")
    best_path = os.path.join(args.output_dir, "unet_resnet34_best.pt")
    latest_path = os.path.join(args.output_dir, "unet_resnet34_latest.pt")
    history_path = os.path.join(args.output_dir, "unet_training_history.json")

    start_epoch, best_iou = 1, 0.0
    history = []
    if args.resume and os.path.exists(ckpt_path):
        try:
            ckpt = torch.load(ckpt_path, map_location=device, weights_only=False)
            model.load_state_dict(ckpt["model_state_dict"])
            optimizer.load_state_dict(ckpt["optimizer_state_dict"])
            scheduler.load_state_dict(ckpt["scheduler_state_dict"])
            start_epoch = ckpt.get("epoch", 0) + 1
            best_iou = ckpt.get("best_iou", 0.0)
            history = ckpt.get("history", [])
            print(f"[U-Net Training] Resumed at epoch {start_epoch} (best IoU {best_iou:.4f})")
        except Exception as e:
            print(f"[U-Net Training] Resume failed ({e}); fresh start.")

    for epoch in range(start_epoch, args.epochs + 1):
        t0 = time.time()
        # --- train ---
        model.train()
        tr_loss = 0.0
        for bi, (imgs, targets) in enumerate(train_loader):
            imgs = imgs.to(device, non_blocking=True)
            targets = targets.to(device, non_blocking=True)
            optimizer.zero_grad()
            with torch.amp.autocast(device_type=device.type, enabled=(scaler is not None)):
                logits = model(imgs)
                loss = criterion(logits, targets)
            if scaler:
                scaler.scale(loss).backward()
                scaler.step(optimizer)
                scaler.update()
            else:
                loss.backward()
                optimizer.step()
            tr_loss += loss.item()
            if (bi + 1) % 25 == 0:
                print(f"  Epoch {epoch:02d} batch {bi+1}/{len(train_loader)} loss {loss.item():.4f}", flush=True)
        scheduler.step()

        # --- validate ---
        model.eval()
        val_loss, val_iou = 0.0, 0.0
        with torch.no_grad():
            for imgs, targets in val_loader:
                imgs = imgs.to(device, non_blocking=True)
                targets = targets.to(device, non_blocking=True)
                with torch.amp.autocast(device_type=device.type, enabled=(device.type == "cuda")):
                    logits = model(imgs)
                    loss = criterion(logits, targets)
                val_loss += loss.item()
                val_iou += iou_score(logits.float(), targets)

        val_loss /= max(len(val_loader), 1)
        val_iou /= max(len(val_loader), 1)
        elapsed = time.time() - t0
        print(f"  EPOCH {epoch:02d}/{args.epochs} | train_loss {tr_loss/len(train_loader):.4f} | "
              f"val_loss {val_loss:.4f} | val_IoU {val_iou:.4f} | {elapsed:.0f}s", flush=True)

        rec = {"epoch": epoch, "train_loss": round(tr_loss / len(train_loader), 4),
               "val_loss": round(val_loss, 4), "val_iou": round(val_iou, 4),
               "duration_seconds": round(elapsed, 1)}
        history.append(rec)

        torch.save(model.state_dict(), latest_path)
        if val_iou >= best_iou:
            best_iou = val_iou
            torch.save(model.state_dict(), best_path)
            print(f"  >>> [NEW BEST] IoU {best_iou:.4f} saved to {best_path}", flush=True)
        torch.save({"epoch": epoch, "model_state_dict": model.state_dict(),
                    "optimizer_state_dict": optimizer.state_dict(),
                    "scheduler_state_dict": scheduler.state_dict(),
                    "best_iou": best_iou, "history": history}, ckpt_path)
        with open(history_path, "w") as f:
            json.dump(history, f, indent=2)

    print(f"[U-Net Training Complete] Best val IoU: {best_iou:.4f} -> {best_path}")


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"[FATAL]: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
